### ISSUE TITLE
White-out in certain Biomes

### ISSUE THREAD

**Issue by AechtRob** [pale-imitations/Magic_Kingdoms#10]
Biomes turn completely white (like 100% opacity white fog!) when you enter them, and are unplayable. So far identified these:

Mountainous Jungle
Sinister Swamp

Setup:
Magic Kingdoms: SOM1.12.2-1.1.14.jar
Installation: Forge 14.23.5.2847 (MC 1.12.2) 
Visuals: Optifine 1.12.2_HD_U_F5 [mod]
WorldGen: LostCities 1.12-2.0.21 (Biomes o Plenty setting) + Biomes o Plenty 1.12.2-7.0.1.2443-universal

**Comment by AechtRob** [comment]
I have experimented with the various mods also running, and I think I've isolated that it is conflicting with Dynamic Surroundings (I'm using 1.12.2-3.6.0.2 of that mod). If I switch off fog processing in that mod, then your Biomes display fine.

I tried providing an alias Biome in Dynamic Surroundings in case it just didn't know what to do: "Mountainous Jungle=Jungle", but that made no difference.

Is your own mod creating fog within your Biomes which then gets summed onto the Dynamic Surroundings own fog to cause a complete white-out? If so, I'd suggest you remove all fog from your own Biomes (as that's how MC vanilla works) and allow users to apply fog using a mod like Dynamic Surroundings instead. You can't blacklist Biomes from Dynamic Surroundings - though maybe they will allow that one day, only Dimensions (do your own Biomes have their own distinct Dimension somehow?).

Best wishes,

**Comment by pale-imitations** [comment]
Thank you for letting me know about this, I've seen in the comments that you've said this is fixed, and I really wish I knew what I did that fixed it or what part of the code was causing the issue. But I'm happy to hear things are running better. I will be revisiting the fog soon tho to add a more gradiented effect when entering the biomes.
