### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by KamiSami** [pale-imitations/Magic_Kingdoms#16]
Hi again, been testing necromancy spells a bit and realized 2 things related to spells so far which would be nice. One is making zombies spawn out of ground, they spawn in being stuck 1 block underground, but it's not too severe when you are on move as they teleport to you, but in tough situation somewhere maybe indoors it may be a problem when they are unable to get out as they seem confused. Second one is about wands/spells overall which would make great addition which is the following: Have spell wheel tell you what the targeted/selected spell is called, as it is hard to memorize icons of the spells. Thanks again for this mod though, even that it has probably some bugs, but nevertheless it seems promising! I am looking forward for more updates! ^^

**Comment by pale-imitations** [comment]
I think that's completely reasonable
