### ISSUE TITLE
Overlay overlap

### ISSUE THREAD

**Issue by zEpiixz** [pale-imitations/Magic_Kingdoms#2]
I think it would be better if you press f3 the overlay from  should vanish so you can read the information ^^

**Comment by pale-imitations** [comment]
I'll see if I can fix that!

**Comment by pale-imitations** [comment]
I think the easiest way to fix this is for the mana overlay to only display while one is holding an item that uses mana, such as a wand.

**Comment by zEpiixz** [comment]
yea i think thats a good idea. Alot of mods do the same
