### ISSUE TITLE
[Feature Request] Config/ore dictionary/chisel compat

### ISSUE THREAD

**Issue by faeldray** [pale-imitations/Magic_Kingdoms#4]
I hope it's alright to ask for these things.

- Config: Especially being able to turn off individual ores since I have other mods adding things like copper, silver, sapphire, and opal.
- Ore dictionary: It would be great if there were more ore dictionary entries (ex. all the gems so they could be used in other mods' recipes). Also, it would be fantastic if recipes from this mod accepted more ore-dictionary materials (ex. any silver ingot can be used to craft the oak wand or any leather (such as Roots' fey leather) can craft the potion bag)
- Chisel compatibility: Adding the metal and gem blocks to Chisel means that even if players can't craft the blocks because of recipe conflicts, they can still use the blocks for decoration. The gem blocks are absolutely gorgeous btw!

**Comment by pale-imitations** [comment]
Thank you, the config file is coming in the next major update, as is the ore dictionary fix, and I'll add chisel to my list to add compatibility with!

**Comment by faeldray** [comment]
Awesome, thanks!

**Comment by faeldray** [comment]
Thanks for adding the config and oredict-ing materials! Is using the ore dictionary in recipes coming soon? I see recipes like void ingots are still using this mod's silver only.
