### ISSUE TITLE
Large ziggurat temple causing huge fps and tps drops

### ISSUE THREAD

**Issue by SeriousCreeper** [pale-imitations/Magic_Kingdoms#5]
Heya,

was just toying around with the mod and noticed that if i approach one of the large temples, both my fps and tps hurt quite a bit. 

Before approaching: https://i.imgur.com/QZidoCC.png 
After approaching: https://i.imgur.com/2ntZq7K.png 

Just tried in an empty instance with just magic kingdoms and some QoL stuff, no optifine, and fps went down to like 5. 

Forge version and PC stats should be visible in the screenshots. Using the latest version of the mod. 

Let me know if you need any other info!

**Comment by pale-imitations** [comment]
I'm planning to add some performance options when I get around to making the config file. Also just as a side question, which texture pack is that? It looks really nice

**Comment by SeriousCreeper** [comment]
It's just the new 1.14 textures in 1.12 :D

**Comment by pale-imitations** [comment]
I really like it, also I managed to figure out what's been causing the lag spikes, and I think I managed to fix it. I'm going to put out a mini-update 1.1.14, let me know if that fixes the issue for you.
