### ISSUE TITLE
Phoenix gives non-existing book(?) and Internal Error, both in server

### ISSUE THREAD

**Issue by KamiSami** [pale-imitations/Magic_Kingdoms#9]
Basically i do all 3 steps to get the Phoenix to spawn, and i right click it and i receive the book, but as soon as i try pick it up from inventory it vanishes, as if i never got the book, same happens with me trying to shear unicorns, i never get the horns even they appear in inventory, but they just vanish as soon as i try pick them up or act as if they are never there... Also, i went and cheated to see how magics work on the mod but to my disappointment i get internal server error immediately as soon as i open wand's magic wheel with V... I am unable to log in the server afterwards unless i restart it, and i cannot send latest log either because for some reason it is  over 637MB in size...

**Comment by pale-imitations** [comment]
When I updated to the newest Forge version it messed up some of my entity interaction code, but this should be fixed in 1.2.2
